apiVersion: v2
name: consumer
version: 0.0.1
description: A Helm chart for Kubernetes Project
appVersion: 0.1.0
keywords:
  - kubernetes
  - producer
  - consumer
  - rabbitmq
maintainers:
  - name: ofir
    email: 75673005+chkp-ofirs@users.noreply.github.com
icon: https://cncf-branding.netlify.app/img/projects/helm/icon/color/helm-icon-color.png
engine: gotpl # The name of the template engine (optional, defaults to gotpl)
type: application
home: https://github.com/ofirshi/k8s-project1
sources:
    - https://github.com/chkp-ofirs?tab=packages

dependencies:
- name: producer
  version: ">=0.0.0-0"
  enabled: true
  repository: file://../producer
- name: rabbitmq 
  repository: "https://charts.bitnami.com/bitnami"
  version: "10.1.12"
  enabled: true
  condition: auth.password="guest", metrics.enabled="true",auth.username="guest",nameOverride="rabbitmq",volumePermissions.enabled="true",auth.erlangCookie="guest"