apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-deployment
  labels:
    app: producer-deployment
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      producer.service: producer
  template:
    metadata:
      labels:
        producer.service: producer
    spec:
      containers:
        - name: producer
          image: ghcr.io/chkp-ofirs/producer:latest
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          args:
            - python
            - producer.py
            - -p
            - "5672"
            - -s
            - rabbitmq
            - -m
            - Hello
            - -r
            - "30"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-deployment
  labels:
    app: consumer-deployment
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      consumer.service: consumer
  template:
    metadata:
      labels:
        consumer.service: consumer
    spec:
      containers:
        - name: consumer
          image: ghcr.io/chkp-ofirs/consumer:latest
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          args:
            - python
            - consumer.py
            - -p
            - "5672"
            - -s
            - rabbitmq