apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    rabbitmq.service/name: rabbitmq
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: "5672"
      port: 5672
      protocol: TCP
      targetPort: 5672
    - name: "15672"
      port: 15672
      protocol: TCP
      targetPort: 15672
  selector:
    rabbitmq.service/name: rabbitmq